### ISSUE TITLE
Listen for changes in minimum level from Seq

### ISSUE THREAD

**Issue by Wedvich** [Wedvich/structured-log-seq-sink#2]
When using an API key to send events , the minimum accepted level for events can be set for that API key in Seq. A header is returned in the HTTP response with the minimum supported level when logging. This sink could use an internal minimum level filter that's updated by whatever Seq gives it.

- [x] Add internal minimum level filter
- [x] Update minimum level with response value from Seq

**Comment by xwipeoutx** [comment]
I'm assuming this is up for grabs now.  Hope so, because I'm working on it.

**Comment by Wedvich** [comment]
Yep, it is. Awesome that you're contributing, looking forward to seeing the
results!

30. jan. 2017 15:48 skrev "Steve Leigh" <notifications@github.com>:
